name: Build Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # ✅ Ensures we use a GitHub-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'  # ✅ Installs Ruby automatically
          bundler-cache: true  # ✅ Speeds up gem installation

      - name: Install Jekyll and dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build