name: Build Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Let GitHub choose, as this now supports Ruby correctly

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@086ffb1a2090c870a3f881cc91ea83aa4243d408  # ✅ Latest stable version
        with:
          ruby-version: '3.2.2'
          bundler-cache: true  # ✅ Caches Ruby gems for faster builds

      - name: Install Jekyll and dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build